name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dutchpsycho
          template: classic
          base: ""
          config_timezone: Asia/Dubai

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          output_action: commit
          committer_branch: generated
          filename: metrics.svg

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dutchpsycho
          template: classic
          base: ""
          config_timezone: Asia/Dubai

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage

          commits_authoring: dutchpsycho, dutchpsycho@users.noreply.github.com

          output_action: commit
          committer_branch: generated
          filename: metrics.languages.svg
